- name: Ensure PostgreSQL is started and enabled
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    state: started

- name: Create PostgreSQL user
  become: true
  ansible.builtin.shell: |
    sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='{{ db_user }}'" | grep -q 1 || \
    sudo -u postgres psql -c "CREATE USER {{ db_user }} WITH PASSWORD '{{ db_password }}';"
  args:
    executable: /bin/bash

- name: Create SonarQube database
  become: true
  ansible.builtin.shell: |
    sudo -u postgres psql -lqt | cut -d \| -f 1 | grep -qw {{ db_name }} || \
    sudo -u postgres psql -c "CREATE DATABASE {{ db_name }} OWNER {{ db_user }} ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' TEMPLATE template0;"
  args:
    executable: /bin/bash

